package com.ikingsnipe.casino.core;
public enum CasinoState {
    INITIALIZING, WALKING_TO_LOCATION, BANKING, IDLE, TRADE_REQUESTED,
    TRADING_WINDOW_1, TRADING_WINDOW_2, PROCESSING_GAME, PAYOUT_PENDING, ERROR_RECOVERY
}
